### ISSUE TITLE
Gulp serve task not found

### ISSUE THREAD

**Issue by ghost** [yoeran/kirby-kit#1]
Hello Yoeran,

thank you for this project! It's really good to learn what's possible with Gulp thanks to your Kirby Kit project. I just have one problem. If I run "gulp serve" from the command line in the root directory I get an error saying there is not serve task. Looking for it I can't find it. 

Here is my package.json and I'm running Node.js 4.2.1.

```
KirbyApp@0.0.0 /Users/<username>/Projects/Gulp/gulp-kirby-kit
├── del@1.2.1
├── gulp@3.9.0
├── gulp-autoprefixer@2.3.1
├── gulp-concat@2.6.0
├── gulp-connect-php@0.0.5
├── gulp-download@0.0.1
├── gulp-imagemin@2.3.0
├── gulp-jshint@1.11.2
├── gulp-livereload@3.8.1
├── gulp-minify-css@0.5.1
├── gulp-modernizr@1.0.0-alpha
├── gulp-plumber@1.0.1
├── gulp-rename@1.2.2
├── gulp-sass@2.0.4
├── gulp-uglify@1.4.2
├── gulp-unzip@0.1.3
├── imagemin-pngquant@4.2.0
├── jshint-stylish@1.0.2
├── node-sass@3.4.1
├── require-dir@0.1.0
├── run-sequence@1.1.4
└── wiredep@2.2.2
```

There was also a problem with gulp-sass. It did not work, becuase node-sass did not find the bindings for libsass. So I had to uninstall it and reinstall with: 

```
npm i gulp-sass@2 --save-dev
```

This should install node-sass 3.3.x or higher which has node 4 support. I guess you simply have to bump the version from 1 to 2.

**Comment by yoeran** [comment]
Hi Mike,

Thanks for the interest in the project and your pull request.
I hope it helps you build some great stuff.
